import uiautomator2 as u2
import time
d = u2.connect('2b334f69')
# d(description="京东").click()
# time.sleep(60)
d(description="浮层活动").click()
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")

d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")
d.xpath('//android.widget.FrameLayout[2]').click()
time.sleep(15)
d.press("back")